version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      github-action-updates:
        patterns:
          - "*"
    schedule:
      interval: weekly
    labels: ["skip-changelog"]

  - package-ecosystem: "uv"
    directory: "/"
    groups:
      uv-updates:
        patterns:
          - "*"
    schedule:
      interval: weekly
    labels: ["skip-changelog"]
