


/* Generated by glib-mkenums. Do not edit */

#include "soup-enum-types.h"
#define LIBSOUP_USE_UNSTABLE_REQUEST_API
#include "soup.h" 
#include "soup-address.h" 
#include "soup-auth.h" 
#include "soup-auth-domain.h" 
#include "soup-auth-domain-basic.h" 
#include "soup-auth-domain-digest.h" 
#include "soup-auth-manager.h" 
#include "soup-cache.h" 
#include "soup-content-decoder.h" 
#include "soup-content-sniffer.h" 
#include "soup-cookie.h" 
#include "soup-cookie-jar.h" 
#include "soup-cookie-jar-db.h" 
#include "soup-cookie-jar-text.h" 
#include "soup-date.h" 
#include "soup-form.h" 
#include "soup-headers.h" 
#include "soup-logger.h" 
#include "soup-message.h" 
#include "soup-message-body.h" 
#include "soup-message-headers.h" 
#include "soup-method.h" 
#include "soup-misc.h" 
#include "soup-multipart.h" 
#include "soup-multipart-input-stream.h" 
#include "soup-password-manager.h" 
#include "soup-portability.h" 
#include "soup-proxy-resolver.h" 
#include "soup-proxy-resolver-default.h" 
#include "soup-proxy-uri-resolver.h" 
#include "soup-request.h" 
#include "soup-request-data.h" 
#include "soup-request-file.h" 
#include "soup-request-http.h" 
#include "soup-requester.h" 
#include "soup-server.h" 
#include "soup-session.h" 
#include "soup-session-async.h" 
#include "soup-session-feature.h" 
#include "soup-session-sync.h" 
#include "soup-socket.h" 
#include "soup-status.h" 
#include "soup-tld.h" 
#include "soup-types.h" 
#include "soup-uri.h" 
#include "soup-value-utils.h" 
#include "soup-websocket.h" 
#include "soup-websocket-connection.h" 
#include "soup-xmlrpc.h" 
#include "soup-xmlrpc-old.h" 
#include "soup-cookie-jar-sqlite.h" 
#include "soup-gnome.h" 
#include "soup-gnome-features.h"

GType
soup_address_family_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { SOUP_ADDRESS_FAMILY_INVALID, "SOUP_ADDRESS_FAMILY_INVALID", "invalid" },
        { SOUP_ADDRESS_FAMILY_IPV4, "SOUP_ADDRESS_FAMILY_IPV4", "ipv4" },
        { SOUP_ADDRESS_FAMILY_IPV6, "SOUP_ADDRESS_FAMILY_IPV6", "ipv6" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("SoupAddressFamily"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
soup_cacheability_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GFlagsValue values[] = {
        { SOUP_CACHE_CACHEABLE, "SOUP_CACHE_CACHEABLE", "cacheable" },
        { SOUP_CACHE_UNCACHEABLE, "SOUP_CACHE_UNCACHEABLE", "uncacheable" },
        { SOUP_CACHE_INVALIDATES, "SOUP_CACHE_INVALIDATES", "invalidates" },
        { SOUP_CACHE_VALIDATES, "SOUP_CACHE_VALIDATES", "validates" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_flags_register_static (g_intern_static_string ("SoupCacheability"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
soup_cache_response_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { SOUP_CACHE_RESPONSE_FRESH, "SOUP_CACHE_RESPONSE_FRESH", "fresh" },
        { SOUP_CACHE_RESPONSE_NEEDS_VALIDATION, "SOUP_CACHE_RESPONSE_NEEDS_VALIDATION", "needs-validation" },
        { SOUP_CACHE_RESPONSE_STALE, "SOUP_CACHE_RESPONSE_STALE", "stale" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("SoupCacheResponse"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
soup_cache_type_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { SOUP_CACHE_SINGLE_USER, "SOUP_CACHE_SINGLE_USER", "single-user" },
        { SOUP_CACHE_SHARED, "SOUP_CACHE_SHARED", "shared" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("SoupCacheType"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
soup_cookie_jar_accept_policy_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { SOUP_COOKIE_JAR_ACCEPT_ALWAYS, "SOUP_COOKIE_JAR_ACCEPT_ALWAYS", "always" },
        { SOUP_COOKIE_JAR_ACCEPT_NEVER, "SOUP_COOKIE_JAR_ACCEPT_NEVER", "never" },
        { SOUP_COOKIE_JAR_ACCEPT_NO_THIRD_PARTY, "SOUP_COOKIE_JAR_ACCEPT_NO_THIRD_PARTY", "no-third-party" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("SoupCookieJarAcceptPolicy"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
soup_date_format_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { SOUP_DATE_HTTP, "SOUP_DATE_HTTP", "http" },
        { SOUP_DATE_COOKIE, "SOUP_DATE_COOKIE", "cookie" },
        { SOUP_DATE_RFC2822, "SOUP_DATE_RFC2822", "rfc2822" },
        { SOUP_DATE_ISO8601_COMPACT, "SOUP_DATE_ISO8601_COMPACT", "iso8601-compact" },
        { SOUP_DATE_ISO8601_FULL, "SOUP_DATE_ISO8601_FULL", "iso8601-full" },
        { SOUP_DATE_ISO8601, "SOUP_DATE_ISO8601", "iso8601" },
        { SOUP_DATE_ISO8601_XMLRPC, "SOUP_DATE_ISO8601_XMLRPC", "iso8601-xmlrpc" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("SoupDateFormat"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
soup_logger_log_level_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { SOUP_LOGGER_LOG_NONE, "SOUP_LOGGER_LOG_NONE", "none" },
        { SOUP_LOGGER_LOG_MINIMAL, "SOUP_LOGGER_LOG_MINIMAL", "minimal" },
        { SOUP_LOGGER_LOG_HEADERS, "SOUP_LOGGER_LOG_HEADERS", "headers" },
        { SOUP_LOGGER_LOG_BODY, "SOUP_LOGGER_LOG_BODY", "body" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("SoupLoggerLogLevel"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
soup_http_version_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { SOUP_HTTP_1_0, "SOUP_HTTP_1_0", "http-1-0" },
        { SOUP_HTTP_1_1, "SOUP_HTTP_1_1", "http-1-1" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("SoupHTTPVersion"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
soup_message_flags_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GFlagsValue values[] = {
        { SOUP_MESSAGE_NO_REDIRECT, "SOUP_MESSAGE_NO_REDIRECT", "no-redirect" },
        { SOUP_MESSAGE_CAN_REBUILD, "SOUP_MESSAGE_CAN_REBUILD", "can-rebuild" },
        { SOUP_MESSAGE_OVERWRITE_CHUNKS, "SOUP_MESSAGE_OVERWRITE_CHUNKS", "overwrite-chunks" },
        { SOUP_MESSAGE_CONTENT_DECODED, "SOUP_MESSAGE_CONTENT_DECODED", "content-decoded" },
        { SOUP_MESSAGE_CERTIFICATE_TRUSTED, "SOUP_MESSAGE_CERTIFICATE_TRUSTED", "certificate-trusted" },
        { SOUP_MESSAGE_NEW_CONNECTION, "SOUP_MESSAGE_NEW_CONNECTION", "new-connection" },
        { SOUP_MESSAGE_IDEMPOTENT, "SOUP_MESSAGE_IDEMPOTENT", "idempotent" },
        { SOUP_MESSAGE_IGNORE_CONNECTION_LIMITS, "SOUP_MESSAGE_IGNORE_CONNECTION_LIMITS", "ignore-connection-limits" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_flags_register_static (g_intern_static_string ("SoupMessageFlags"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
soup_message_priority_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { SOUP_MESSAGE_PRIORITY_VERY_LOW, "SOUP_MESSAGE_PRIORITY_VERY_LOW", "very-low" },
        { SOUP_MESSAGE_PRIORITY_LOW, "SOUP_MESSAGE_PRIORITY_LOW", "low" },
        { SOUP_MESSAGE_PRIORITY_NORMAL, "SOUP_MESSAGE_PRIORITY_NORMAL", "normal" },
        { SOUP_MESSAGE_PRIORITY_HIGH, "SOUP_MESSAGE_PRIORITY_HIGH", "high" },
        { SOUP_MESSAGE_PRIORITY_VERY_HIGH, "SOUP_MESSAGE_PRIORITY_VERY_HIGH", "very-high" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("SoupMessagePriority"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
soup_memory_use_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { SOUP_MEMORY_STATIC, "SOUP_MEMORY_STATIC", "static" },
        { SOUP_MEMORY_TAKE, "SOUP_MEMORY_TAKE", "take" },
        { SOUP_MEMORY_COPY, "SOUP_MEMORY_COPY", "copy" },
        { SOUP_MEMORY_TEMPORARY, "SOUP_MEMORY_TEMPORARY", "temporary" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("SoupMemoryUse"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
soup_message_headers_type_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { SOUP_MESSAGE_HEADERS_REQUEST, "SOUP_MESSAGE_HEADERS_REQUEST", "request" },
        { SOUP_MESSAGE_HEADERS_RESPONSE, "SOUP_MESSAGE_HEADERS_RESPONSE", "response" },
        { SOUP_MESSAGE_HEADERS_MULTIPART, "SOUP_MESSAGE_HEADERS_MULTIPART", "multipart" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("SoupMessageHeadersType"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
soup_encoding_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { SOUP_ENCODING_UNRECOGNIZED, "SOUP_ENCODING_UNRECOGNIZED", "unrecognized" },
        { SOUP_ENCODING_NONE, "SOUP_ENCODING_NONE", "none" },
        { SOUP_ENCODING_CONTENT_LENGTH, "SOUP_ENCODING_CONTENT_LENGTH", "content-length" },
        { SOUP_ENCODING_EOF, "SOUP_ENCODING_EOF", "eof" },
        { SOUP_ENCODING_CHUNKED, "SOUP_ENCODING_CHUNKED", "chunked" },
        { SOUP_ENCODING_BYTERANGES, "SOUP_ENCODING_BYTERANGES", "byteranges" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("SoupEncoding"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
soup_expectation_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GFlagsValue values[] = {
        { SOUP_EXPECTATION_UNRECOGNIZED, "SOUP_EXPECTATION_UNRECOGNIZED", "unrecognized" },
        { SOUP_EXPECTATION_CONTINUE, "SOUP_EXPECTATION_CONTINUE", "continue" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_flags_register_static (g_intern_static_string ("SoupExpectation"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
soup_connection_state_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { SOUP_CONNECTION_NEW, "SOUP_CONNECTION_NEW", "new" },
        { SOUP_CONNECTION_CONNECTING, "SOUP_CONNECTION_CONNECTING", "connecting" },
        { SOUP_CONNECTION_IDLE, "SOUP_CONNECTION_IDLE", "idle" },
        { SOUP_CONNECTION_IN_USE, "SOUP_CONNECTION_IN_USE", "in-use" },
        { SOUP_CONNECTION_REMOTE_DISCONNECTED, "SOUP_CONNECTION_REMOTE_DISCONNECTED", "remote-disconnected" },
        { SOUP_CONNECTION_DISCONNECTED, "SOUP_CONNECTION_DISCONNECTED", "disconnected" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("SoupConnectionState"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
soup_requester_error_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { SOUP_REQUESTER_ERROR_BAD_URI, "SOUP_REQUESTER_ERROR_BAD_URI", "bad-uri" },
        { SOUP_REQUESTER_ERROR_UNSUPPORTED_URI_SCHEME, "SOUP_REQUESTER_ERROR_UNSUPPORTED_URI_SCHEME", "unsupported-uri-scheme" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("SoupRequesterError"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
soup_server_listen_options_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GFlagsValue values[] = {
        { SOUP_SERVER_LISTEN_HTTPS, "SOUP_SERVER_LISTEN_HTTPS", "https" },
        { SOUP_SERVER_LISTEN_IPV4_ONLY, "SOUP_SERVER_LISTEN_IPV4_ONLY", "ipv4-only" },
        { SOUP_SERVER_LISTEN_IPV6_ONLY, "SOUP_SERVER_LISTEN_IPV6_ONLY", "ipv6-only" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_flags_register_static (g_intern_static_string ("SoupServerListenOptions"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
soup_request_error_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { SOUP_REQUEST_ERROR_BAD_URI, "SOUP_REQUEST_ERROR_BAD_URI", "bad-uri" },
        { SOUP_REQUEST_ERROR_UNSUPPORTED_URI_SCHEME, "SOUP_REQUEST_ERROR_UNSUPPORTED_URI_SCHEME", "unsupported-uri-scheme" },
        { SOUP_REQUEST_ERROR_PARSING, "SOUP_REQUEST_ERROR_PARSING", "parsing" },
        { SOUP_REQUEST_ERROR_ENCODING, "SOUP_REQUEST_ERROR_ENCODING", "encoding" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("SoupRequestError"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
soup_socket_io_status_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { SOUP_SOCKET_OK, "SOUP_SOCKET_OK", "ok" },
        { SOUP_SOCKET_WOULD_BLOCK, "SOUP_SOCKET_WOULD_BLOCK", "would-block" },
        { SOUP_SOCKET_EOF, "SOUP_SOCKET_EOF", "eof" },
        { SOUP_SOCKET_ERROR, "SOUP_SOCKET_ERROR", "error" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("SoupSocketIOStatus"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
soup_status_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { SOUP_STATUS_NONE, "SOUP_STATUS_NONE", "none" },
        { SOUP_STATUS_CANCELLED, "SOUP_STATUS_CANCELLED", "cancelled" },
        { SOUP_STATUS_CANT_RESOLVE, "SOUP_STATUS_CANT_RESOLVE", "cant-resolve" },
        { SOUP_STATUS_CANT_RESOLVE_PROXY, "SOUP_STATUS_CANT_RESOLVE_PROXY", "cant-resolve-proxy" },
        { SOUP_STATUS_CANT_CONNECT, "SOUP_STATUS_CANT_CONNECT", "cant-connect" },
        { SOUP_STATUS_CANT_CONNECT_PROXY, "SOUP_STATUS_CANT_CONNECT_PROXY", "cant-connect-proxy" },
        { SOUP_STATUS_SSL_FAILED, "SOUP_STATUS_SSL_FAILED", "ssl-failed" },
        { SOUP_STATUS_IO_ERROR, "SOUP_STATUS_IO_ERROR", "io-error" },
        { SOUP_STATUS_MALFORMED, "SOUP_STATUS_MALFORMED", "malformed" },
        { SOUP_STATUS_TRY_AGAIN, "SOUP_STATUS_TRY_AGAIN", "try-again" },
        { SOUP_STATUS_TOO_MANY_REDIRECTS, "SOUP_STATUS_TOO_MANY_REDIRECTS", "too-many-redirects" },
        { SOUP_STATUS_TLS_FAILED, "SOUP_STATUS_TLS_FAILED", "tls-failed" },
        { SOUP_STATUS_CONTINUE, "SOUP_STATUS_CONTINUE", "continue" },
        { SOUP_STATUS_SWITCHING_PROTOCOLS, "SOUP_STATUS_SWITCHING_PROTOCOLS", "switching-protocols" },
        { SOUP_STATUS_PROCESSING, "SOUP_STATUS_PROCESSING", "processing" },
        { SOUP_STATUS_OK, "SOUP_STATUS_OK", "ok" },
        { SOUP_STATUS_CREATED, "SOUP_STATUS_CREATED", "created" },
        { SOUP_STATUS_ACCEPTED, "SOUP_STATUS_ACCEPTED", "accepted" },
        { SOUP_STATUS_NON_AUTHORITATIVE, "SOUP_STATUS_NON_AUTHORITATIVE", "non-authoritative" },
        { SOUP_STATUS_NO_CONTENT, "SOUP_STATUS_NO_CONTENT", "no-content" },
        { SOUP_STATUS_RESET_CONTENT, "SOUP_STATUS_RESET_CONTENT", "reset-content" },
        { SOUP_STATUS_PARTIAL_CONTENT, "SOUP_STATUS_PARTIAL_CONTENT", "partial-content" },
        { SOUP_STATUS_MULTI_STATUS, "SOUP_STATUS_MULTI_STATUS", "multi-status" },
        { SOUP_STATUS_MULTIPLE_CHOICES, "SOUP_STATUS_MULTIPLE_CHOICES", "multiple-choices" },
        { SOUP_STATUS_MOVED_PERMANENTLY, "SOUP_STATUS_MOVED_PERMANENTLY", "moved-permanently" },
        { SOUP_STATUS_FOUND, "SOUP_STATUS_FOUND", "found" },
        { SOUP_STATUS_MOVED_TEMPORARILY, "SOUP_STATUS_MOVED_TEMPORARILY", "moved-temporarily" },
        { SOUP_STATUS_SEE_OTHER, "SOUP_STATUS_SEE_OTHER", "see-other" },
        { SOUP_STATUS_NOT_MODIFIED, "SOUP_STATUS_NOT_MODIFIED", "not-modified" },
        { SOUP_STATUS_USE_PROXY, "SOUP_STATUS_USE_PROXY", "use-proxy" },
        { SOUP_STATUS_NOT_APPEARING_IN_THIS_PROTOCOL, "SOUP_STATUS_NOT_APPEARING_IN_THIS_PROTOCOL", "not-appearing-in-this-protocol" },
        { SOUP_STATUS_TEMPORARY_REDIRECT, "SOUP_STATUS_TEMPORARY_REDIRECT", "temporary-redirect" },
        { SOUP_STATUS_BAD_REQUEST, "SOUP_STATUS_BAD_REQUEST", "bad-request" },
        { SOUP_STATUS_UNAUTHORIZED, "SOUP_STATUS_UNAUTHORIZED", "unauthorized" },
        { SOUP_STATUS_PAYMENT_REQUIRED, "SOUP_STATUS_PAYMENT_REQUIRED", "payment-required" },
        { SOUP_STATUS_FORBIDDEN, "SOUP_STATUS_FORBIDDEN", "forbidden" },
        { SOUP_STATUS_NOT_FOUND, "SOUP_STATUS_NOT_FOUND", "not-found" },
        { SOUP_STATUS_METHOD_NOT_ALLOWED, "SOUP_STATUS_METHOD_NOT_ALLOWED", "method-not-allowed" },
        { SOUP_STATUS_NOT_ACCEPTABLE, "SOUP_STATUS_NOT_ACCEPTABLE", "not-acceptable" },
        { SOUP_STATUS_PROXY_AUTHENTICATION_REQUIRED, "SOUP_STATUS_PROXY_AUTHENTICATION_REQUIRED", "proxy-authentication-required" },
        { SOUP_STATUS_PROXY_UNAUTHORIZED, "SOUP_STATUS_PROXY_UNAUTHORIZED", "proxy-unauthorized" },
        { SOUP_STATUS_REQUEST_TIMEOUT, "SOUP_STATUS_REQUEST_TIMEOUT", "request-timeout" },
        { SOUP_STATUS_CONFLICT, "SOUP_STATUS_CONFLICT", "conflict" },
        { SOUP_STATUS_GONE, "SOUP_STATUS_GONE", "gone" },
        { SOUP_STATUS_LENGTH_REQUIRED, "SOUP_STATUS_LENGTH_REQUIRED", "length-required" },
        { SOUP_STATUS_PRECONDITION_FAILED, "SOUP_STATUS_PRECONDITION_FAILED", "precondition-failed" },
        { SOUP_STATUS_REQUEST_ENTITY_TOO_LARGE, "SOUP_STATUS_REQUEST_ENTITY_TOO_LARGE", "request-entity-too-large" },
        { SOUP_STATUS_REQUEST_URI_TOO_LONG, "SOUP_STATUS_REQUEST_URI_TOO_LONG", "request-uri-too-long" },
        { SOUP_STATUS_UNSUPPORTED_MEDIA_TYPE, "SOUP_STATUS_UNSUPPORTED_MEDIA_TYPE", "unsupported-media-type" },
        { SOUP_STATUS_REQUESTED_RANGE_NOT_SATISFIABLE, "SOUP_STATUS_REQUESTED_RANGE_NOT_SATISFIABLE", "requested-range-not-satisfiable" },
        { SOUP_STATUS_INVALID_RANGE, "SOUP_STATUS_INVALID_RANGE", "invalid-range" },
        { SOUP_STATUS_EXPECTATION_FAILED, "SOUP_STATUS_EXPECTATION_FAILED", "expectation-failed" },
        { SOUP_STATUS_UNPROCESSABLE_ENTITY, "SOUP_STATUS_UNPROCESSABLE_ENTITY", "unprocessable-entity" },
        { SOUP_STATUS_LOCKED, "SOUP_STATUS_LOCKED", "locked" },
        { SOUP_STATUS_FAILED_DEPENDENCY, "SOUP_STATUS_FAILED_DEPENDENCY", "failed-dependency" },
        { SOUP_STATUS_INTERNAL_SERVER_ERROR, "SOUP_STATUS_INTERNAL_SERVER_ERROR", "internal-server-error" },
        { SOUP_STATUS_NOT_IMPLEMENTED, "SOUP_STATUS_NOT_IMPLEMENTED", "not-implemented" },
        { SOUP_STATUS_BAD_GATEWAY, "SOUP_STATUS_BAD_GATEWAY", "bad-gateway" },
        { SOUP_STATUS_SERVICE_UNAVAILABLE, "SOUP_STATUS_SERVICE_UNAVAILABLE", "service-unavailable" },
        { SOUP_STATUS_GATEWAY_TIMEOUT, "SOUP_STATUS_GATEWAY_TIMEOUT", "gateway-timeout" },
        { SOUP_STATUS_HTTP_VERSION_NOT_SUPPORTED, "SOUP_STATUS_HTTP_VERSION_NOT_SUPPORTED", "http-version-not-supported" },
        { SOUP_STATUS_INSUFFICIENT_STORAGE, "SOUP_STATUS_INSUFFICIENT_STORAGE", "insufficient-storage" },
        { SOUP_STATUS_NOT_EXTENDED, "SOUP_STATUS_NOT_EXTENDED", "not-extended" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("SoupStatus"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
soup_known_status_code_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { SOUP_KNOWN_STATUS_CODE_NONE, "SOUP_KNOWN_STATUS_CODE_NONE", "none" },
        { SOUP_KNOWN_STATUS_CODE_CANCELLED, "SOUP_KNOWN_STATUS_CODE_CANCELLED", "cancelled" },
        { SOUP_KNOWN_STATUS_CODE_CANT_RESOLVE, "SOUP_KNOWN_STATUS_CODE_CANT_RESOLVE", "cant-resolve" },
        { SOUP_KNOWN_STATUS_CODE_CANT_RESOLVE_PROXY, "SOUP_KNOWN_STATUS_CODE_CANT_RESOLVE_PROXY", "cant-resolve-proxy" },
        { SOUP_KNOWN_STATUS_CODE_CANT_CONNECT, "SOUP_KNOWN_STATUS_CODE_CANT_CONNECT", "cant-connect" },
        { SOUP_KNOWN_STATUS_CODE_CANT_CONNECT_PROXY, "SOUP_KNOWN_STATUS_CODE_CANT_CONNECT_PROXY", "cant-connect-proxy" },
        { SOUP_KNOWN_STATUS_CODE_SSL_FAILED, "SOUP_KNOWN_STATUS_CODE_SSL_FAILED", "ssl-failed" },
        { SOUP_KNOWN_STATUS_CODE_IO_ERROR, "SOUP_KNOWN_STATUS_CODE_IO_ERROR", "io-error" },
        { SOUP_KNOWN_STATUS_CODE_MALFORMED, "SOUP_KNOWN_STATUS_CODE_MALFORMED", "malformed" },
        { SOUP_KNOWN_STATUS_CODE_TRY_AGAIN, "SOUP_KNOWN_STATUS_CODE_TRY_AGAIN", "try-again" },
        { SOUP_KNOWN_STATUS_CODE_TOO_MANY_REDIRECTS, "SOUP_KNOWN_STATUS_CODE_TOO_MANY_REDIRECTS", "too-many-redirects" },
        { SOUP_KNOWN_STATUS_CODE_TLS_FAILED, "SOUP_KNOWN_STATUS_CODE_TLS_FAILED", "tls-failed" },
        { SOUP_KNOWN_STATUS_CODE_CONTINUE, "SOUP_KNOWN_STATUS_CODE_CONTINUE", "continue" },
        { SOUP_KNOWN_STATUS_CODE_SWITCHING_PROTOCOLS, "SOUP_KNOWN_STATUS_CODE_SWITCHING_PROTOCOLS", "switching-protocols" },
        { SOUP_KNOWN_STATUS_CODE_PROCESSING, "SOUP_KNOWN_STATUS_CODE_PROCESSING", "processing" },
        { SOUP_KNOWN_STATUS_CODE_OK, "SOUP_KNOWN_STATUS_CODE_OK", "ok" },
        { SOUP_KNOWN_STATUS_CODE_CREATED, "SOUP_KNOWN_STATUS_CODE_CREATED", "created" },
        { SOUP_KNOWN_STATUS_CODE_ACCEPTED, "SOUP_KNOWN_STATUS_CODE_ACCEPTED", "accepted" },
        { SOUP_KNOWN_STATUS_CODE_NON_AUTHORITATIVE, "SOUP_KNOWN_STATUS_CODE_NON_AUTHORITATIVE", "non-authoritative" },
        { SOUP_KNOWN_STATUS_CODE_NO_CONTENT, "SOUP_KNOWN_STATUS_CODE_NO_CONTENT", "no-content" },
        { SOUP_KNOWN_STATUS_CODE_RESET_CONTENT, "SOUP_KNOWN_STATUS_CODE_RESET_CONTENT", "reset-content" },
        { SOUP_KNOWN_STATUS_CODE_PARTIAL_CONTENT, "SOUP_KNOWN_STATUS_CODE_PARTIAL_CONTENT", "partial-content" },
        { SOUP_KNOWN_STATUS_CODE_MULTI_STATUS, "SOUP_KNOWN_STATUS_CODE_MULTI_STATUS", "multi-status" },
        { SOUP_KNOWN_STATUS_CODE_MULTIPLE_CHOICES, "SOUP_KNOWN_STATUS_CODE_MULTIPLE_CHOICES", "multiple-choices" },
        { SOUP_KNOWN_STATUS_CODE_MOVED_PERMANENTLY, "SOUP_KNOWN_STATUS_CODE_MOVED_PERMANENTLY", "moved-permanently" },
        { SOUP_KNOWN_STATUS_CODE_FOUND, "SOUP_KNOWN_STATUS_CODE_FOUND", "found" },
        { SOUP_KNOWN_STATUS_CODE_MOVED_TEMPORARILY, "SOUP_KNOWN_STATUS_CODE_MOVED_TEMPORARILY", "moved-temporarily" },
        { SOUP_KNOWN_STATUS_CODE_SEE_OTHER, "SOUP_KNOWN_STATUS_CODE_SEE_OTHER", "see-other" },
        { SOUP_KNOWN_STATUS_CODE_NOT_MODIFIED, "SOUP_KNOWN_STATUS_CODE_NOT_MODIFIED", "not-modified" },
        { SOUP_KNOWN_STATUS_CODE_USE_PROXY, "SOUP_KNOWN_STATUS_CODE_USE_PROXY", "use-proxy" },
        { SOUP_KNOWN_STATUS_CODE_NOT_APPEARING_IN_THIS_PROTOCOL, "SOUP_KNOWN_STATUS_CODE_NOT_APPEARING_IN_THIS_PROTOCOL", "not-appearing-in-this-protocol" },
        { SOUP_KNOWN_STATUS_CODE_TEMPORARY_REDIRECT, "SOUP_KNOWN_STATUS_CODE_TEMPORARY_REDIRECT", "temporary-redirect" },
        { SOUP_KNOWN_STATUS_CODE_BAD_REQUEST, "SOUP_KNOWN_STATUS_CODE_BAD_REQUEST", "bad-request" },
        { SOUP_KNOWN_STATUS_CODE_UNAUTHORIZED, "SOUP_KNOWN_STATUS_CODE_UNAUTHORIZED", "unauthorized" },
        { SOUP_KNOWN_STATUS_CODE_PAYMENT_REQUIRED, "SOUP_KNOWN_STATUS_CODE_PAYMENT_REQUIRED", "payment-required" },
        { SOUP_KNOWN_STATUS_CODE_FORBIDDEN, "SOUP_KNOWN_STATUS_CODE_FORBIDDEN", "forbidden" },
        { SOUP_KNOWN_STATUS_CODE_NOT_FOUND, "SOUP_KNOWN_STATUS_CODE_NOT_FOUND", "not-found" },
        { SOUP_KNOWN_STATUS_CODE_METHOD_NOT_ALLOWED, "SOUP_KNOWN_STATUS_CODE_METHOD_NOT_ALLOWED", "method-not-allowed" },
        { SOUP_KNOWN_STATUS_CODE_NOT_ACCEPTABLE, "SOUP_KNOWN_STATUS_CODE_NOT_ACCEPTABLE", "not-acceptable" },
        { SOUP_KNOWN_STATUS_CODE_PROXY_AUTHENTICATION_REQUIRED, "SOUP_KNOWN_STATUS_CODE_PROXY_AUTHENTICATION_REQUIRED", "proxy-authentication-required" },
        { SOUP_KNOWN_STATUS_CODE_PROXY_UNAUTHORIZED, "SOUP_KNOWN_STATUS_CODE_PROXY_UNAUTHORIZED", "proxy-unauthorized" },
        { SOUP_KNOWN_STATUS_CODE_REQUEST_TIMEOUT, "SOUP_KNOWN_STATUS_CODE_REQUEST_TIMEOUT", "request-timeout" },
        { SOUP_KNOWN_STATUS_CODE_CONFLICT, "SOUP_KNOWN_STATUS_CODE_CONFLICT", "conflict" },
        { SOUP_KNOWN_STATUS_CODE_GONE, "SOUP_KNOWN_STATUS_CODE_GONE", "gone" },
        { SOUP_KNOWN_STATUS_CODE_LENGTH_REQUIRED, "SOUP_KNOWN_STATUS_CODE_LENGTH_REQUIRED", "length-required" },
        { SOUP_KNOWN_STATUS_CODE_PRECONDITION_FAILED, "SOUP_KNOWN_STATUS_CODE_PRECONDITION_FAILED", "precondition-failed" },
        { SOUP_KNOWN_STATUS_CODE_REQUEST_ENTITY_TOO_LARGE, "SOUP_KNOWN_STATUS_CODE_REQUEST_ENTITY_TOO_LARGE", "request-entity-too-large" },
        { SOUP_KNOWN_STATUS_CODE_REQUEST_URI_TOO_LONG, "SOUP_KNOWN_STATUS_CODE_REQUEST_URI_TOO_LONG", "request-uri-too-long" },
        { SOUP_KNOWN_STATUS_CODE_UNSUPPORTED_MEDIA_TYPE, "SOUP_KNOWN_STATUS_CODE_UNSUPPORTED_MEDIA_TYPE", "unsupported-media-type" },
        { SOUP_KNOWN_STATUS_CODE_REQUESTED_RANGE_NOT_SATISFIABLE, "SOUP_KNOWN_STATUS_CODE_REQUESTED_RANGE_NOT_SATISFIABLE", "requested-range-not-satisfiable" },
        { SOUP_KNOWN_STATUS_CODE_INVALID_RANGE, "SOUP_KNOWN_STATUS_CODE_INVALID_RANGE", "invalid-range" },
        { SOUP_KNOWN_STATUS_CODE_EXPECTATION_FAILED, "SOUP_KNOWN_STATUS_CODE_EXPECTATION_FAILED", "expectation-failed" },
        { SOUP_KNOWN_STATUS_CODE_UNPROCESSABLE_ENTITY, "SOUP_KNOWN_STATUS_CODE_UNPROCESSABLE_ENTITY", "unprocessable-entity" },
        { SOUP_KNOWN_STATUS_CODE_LOCKED, "SOUP_KNOWN_STATUS_CODE_LOCKED", "locked" },
        { SOUP_KNOWN_STATUS_CODE_FAILED_DEPENDENCY, "SOUP_KNOWN_STATUS_CODE_FAILED_DEPENDENCY", "failed-dependency" },
        { SOUP_KNOWN_STATUS_CODE_INTERNAL_SERVER_ERROR, "SOUP_KNOWN_STATUS_CODE_INTERNAL_SERVER_ERROR", "internal-server-error" },
        { SOUP_KNOWN_STATUS_CODE_NOT_IMPLEMENTED, "SOUP_KNOWN_STATUS_CODE_NOT_IMPLEMENTED", "not-implemented" },
        { SOUP_KNOWN_STATUS_CODE_BAD_GATEWAY, "SOUP_KNOWN_STATUS_CODE_BAD_GATEWAY", "bad-gateway" },
        { SOUP_KNOWN_STATUS_CODE_SERVICE_UNAVAILABLE, "SOUP_KNOWN_STATUS_CODE_SERVICE_UNAVAILABLE", "service-unavailable" },
        { SOUP_KNOWN_STATUS_CODE_GATEWAY_TIMEOUT, "SOUP_KNOWN_STATUS_CODE_GATEWAY_TIMEOUT", "gateway-timeout" },
        { SOUP_KNOWN_STATUS_CODE_HTTP_VERSION_NOT_SUPPORTED, "SOUP_KNOWN_STATUS_CODE_HTTP_VERSION_NOT_SUPPORTED", "http-version-not-supported" },
        { SOUP_KNOWN_STATUS_CODE_INSUFFICIENT_STORAGE, "SOUP_KNOWN_STATUS_CODE_INSUFFICIENT_STORAGE", "insufficient-storage" },
        { SOUP_KNOWN_STATUS_CODE_NOT_EXTENDED, "SOUP_KNOWN_STATUS_CODE_NOT_EXTENDED", "not-extended" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("SoupKnownStatusCode"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
soup_tld_error_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { SOUP_TLD_ERROR_INVALID_HOSTNAME, "SOUP_TLD_ERROR_INVALID_HOSTNAME", "invalid-hostname" },
        { SOUP_TLD_ERROR_IS_IP_ADDRESS, "SOUP_TLD_ERROR_IS_IP_ADDRESS", "is-ip-address" },
        { SOUP_TLD_ERROR_NOT_ENOUGH_DOMAINS, "SOUP_TLD_ERROR_NOT_ENOUGH_DOMAINS", "not-enough-domains" },
        { SOUP_TLD_ERROR_NO_BASE_DOMAIN, "SOUP_TLD_ERROR_NO_BASE_DOMAIN", "no-base-domain" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("SoupTLDError"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
soup_websocket_error_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { SOUP_WEBSOCKET_ERROR_FAILED, "SOUP_WEBSOCKET_ERROR_FAILED", "failed" },
        { SOUP_WEBSOCKET_ERROR_NOT_WEBSOCKET, "SOUP_WEBSOCKET_ERROR_NOT_WEBSOCKET", "not-websocket" },
        { SOUP_WEBSOCKET_ERROR_BAD_HANDSHAKE, "SOUP_WEBSOCKET_ERROR_BAD_HANDSHAKE", "bad-handshake" },
        { SOUP_WEBSOCKET_ERROR_BAD_ORIGIN, "SOUP_WEBSOCKET_ERROR_BAD_ORIGIN", "bad-origin" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("SoupWebsocketError"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
soup_websocket_connection_type_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { SOUP_WEBSOCKET_CONNECTION_UNKNOWN, "SOUP_WEBSOCKET_CONNECTION_UNKNOWN", "unknown" },
        { SOUP_WEBSOCKET_CONNECTION_CLIENT, "SOUP_WEBSOCKET_CONNECTION_CLIENT", "client" },
        { SOUP_WEBSOCKET_CONNECTION_SERVER, "SOUP_WEBSOCKET_CONNECTION_SERVER", "server" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("SoupWebsocketConnectionType"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
soup_websocket_data_type_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { SOUP_WEBSOCKET_DATA_TEXT, "SOUP_WEBSOCKET_DATA_TEXT", "text" },
        { SOUP_WEBSOCKET_DATA_BINARY, "SOUP_WEBSOCKET_DATA_BINARY", "binary" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("SoupWebsocketDataType"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
soup_websocket_close_code_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { SOUP_WEBSOCKET_CLOSE_NORMAL, "SOUP_WEBSOCKET_CLOSE_NORMAL", "normal" },
        { SOUP_WEBSOCKET_CLOSE_GOING_AWAY, "SOUP_WEBSOCKET_CLOSE_GOING_AWAY", "going-away" },
        { SOUP_WEBSOCKET_CLOSE_PROTOCOL_ERROR, "SOUP_WEBSOCKET_CLOSE_PROTOCOL_ERROR", "protocol-error" },
        { SOUP_WEBSOCKET_CLOSE_UNSUPPORTED_DATA, "SOUP_WEBSOCKET_CLOSE_UNSUPPORTED_DATA", "unsupported-data" },
        { SOUP_WEBSOCKET_CLOSE_NO_STATUS, "SOUP_WEBSOCKET_CLOSE_NO_STATUS", "no-status" },
        { SOUP_WEBSOCKET_CLOSE_ABNORMAL, "SOUP_WEBSOCKET_CLOSE_ABNORMAL", "abnormal" },
        { SOUP_WEBSOCKET_CLOSE_BAD_DATA, "SOUP_WEBSOCKET_CLOSE_BAD_DATA", "bad-data" },
        { SOUP_WEBSOCKET_CLOSE_POLICY_VIOLATION, "SOUP_WEBSOCKET_CLOSE_POLICY_VIOLATION", "policy-violation" },
        { SOUP_WEBSOCKET_CLOSE_TOO_BIG, "SOUP_WEBSOCKET_CLOSE_TOO_BIG", "too-big" },
        { SOUP_WEBSOCKET_CLOSE_NO_EXTENSION, "SOUP_WEBSOCKET_CLOSE_NO_EXTENSION", "no-extension" },
        { SOUP_WEBSOCKET_CLOSE_SERVER_ERROR, "SOUP_WEBSOCKET_CLOSE_SERVER_ERROR", "server-error" },
        { SOUP_WEBSOCKET_CLOSE_TLS_HANDSHAKE, "SOUP_WEBSOCKET_CLOSE_TLS_HANDSHAKE", "tls-handshake" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("SoupWebsocketCloseCode"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
soup_websocket_state_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { SOUP_WEBSOCKET_STATE_OPEN, "SOUP_WEBSOCKET_STATE_OPEN", "open" },
        { SOUP_WEBSOCKET_STATE_CLOSING, "SOUP_WEBSOCKET_STATE_CLOSING", "closing" },
        { SOUP_WEBSOCKET_STATE_CLOSED, "SOUP_WEBSOCKET_STATE_CLOSED", "closed" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("SoupWebsocketState"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
soup_xmlrpc_error_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { SOUP_XMLRPC_ERROR_ARGUMENTS, "SOUP_XMLRPC_ERROR_ARGUMENTS", "arguments" },
        { SOUP_XMLRPC_ERROR_RETVAL, "SOUP_XMLRPC_ERROR_RETVAL", "retval" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("SoupXMLRPCError"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}
GType
soup_xmlrpc_fault_get_type (void)
{
  static volatile gsize g_define_type_id__volatile = 0;

  if (g_once_init_enter (&g_define_type_id__volatile))
    {
      static const GEnumValue values[] = {
        { SOUP_XMLRPC_FAULT_PARSE_ERROR_NOT_WELL_FORMED, "SOUP_XMLRPC_FAULT_PARSE_ERROR_NOT_WELL_FORMED", "parse-error-not-well-formed" },
        { SOUP_XMLRPC_FAULT_PARSE_ERROR_UNSUPPORTED_ENCODING, "SOUP_XMLRPC_FAULT_PARSE_ERROR_UNSUPPORTED_ENCODING", "parse-error-unsupported-encoding" },
        { SOUP_XMLRPC_FAULT_PARSE_ERROR_INVALID_CHARACTER_FOR_ENCODING, "SOUP_XMLRPC_FAULT_PARSE_ERROR_INVALID_CHARACTER_FOR_ENCODING", "parse-error-invalid-character-for-encoding" },
        { SOUP_XMLRPC_FAULT_SERVER_ERROR_INVALID_XML_RPC, "SOUP_XMLRPC_FAULT_SERVER_ERROR_INVALID_XML_RPC", "server-error-invalid-xml-rpc" },
        { SOUP_XMLRPC_FAULT_SERVER_ERROR_REQUESTED_METHOD_NOT_FOUND, "SOUP_XMLRPC_FAULT_SERVER_ERROR_REQUESTED_METHOD_NOT_FOUND", "server-error-requested-method-not-found" },
        { SOUP_XMLRPC_FAULT_SERVER_ERROR_INVALID_METHOD_PARAMETERS, "SOUP_XMLRPC_FAULT_SERVER_ERROR_INVALID_METHOD_PARAMETERS", "server-error-invalid-method-parameters" },
        { SOUP_XMLRPC_FAULT_SERVER_ERROR_INTERNAL_XML_RPC_ERROR, "SOUP_XMLRPC_FAULT_SERVER_ERROR_INTERNAL_XML_RPC_ERROR", "server-error-internal-xml-rpc-error" },
        { SOUP_XMLRPC_FAULT_APPLICATION_ERROR, "SOUP_XMLRPC_FAULT_APPLICATION_ERROR", "application-error" },
        { SOUP_XMLRPC_FAULT_SYSTEM_ERROR, "SOUP_XMLRPC_FAULT_SYSTEM_ERROR", "system-error" },
        { SOUP_XMLRPC_FAULT_TRANSPORT_ERROR, "SOUP_XMLRPC_FAULT_TRANSPORT_ERROR", "transport-error" },
        { 0, NULL, NULL }
      };
      GType g_define_type_id =
        g_enum_register_static (g_intern_static_string ("SoupXMLRPCFault"), values);
      g_once_init_leave (&g_define_type_id__volatile, g_define_type_id);
    }

  return g_define_type_id__volatile;
}



