/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define ALIGNOF_GUINT32 4

#define ALIGNOF_GUINT64 8

#define ALIGNOF_UNSIGNED_LONG 4

#define BROKEN_POLL

// #define DLL_EXPORT

// #define ENABLE_NLS 1

#define EXEEXT ".exe"

#define GETTEXT_PACKAGE "glib20"

#define GLIB_BINARY_AGE 5800

#define GLIB_INTERFACE_AGE 0

#define GLIB_LOCALE_DIR "c:/gtk-build/_bld/vs2017/gtk/Win32/release/share/locale"

#define GLIB_MAJOR_VERSION 2

#define GLIB_MICRO_VERSION 0

#define GLIB_MINOR_VERSION 58

#undef HAVE_C99_SNPRINTF

#undef HAVE_C99_VSNPRINTF

#define HAVE_DCGETTEXT 1

#define HAVE_DLFCN_H 1

#define HAVE_FLOAT_H 1

#define HAVE_GETTEXT 1

#define HAVE_IF_INDEXTONAME 1

#define HAVE_IF_NAMETOINDEX 1

#define HAVE_INTMAX_T 1

#define HAVE_INTTYPES_H 1

#define HAVE_INTTYPES_H_WITH_UINTMAX 1

#define HAVE_LIMITS_H 1

#define HAVE_LOCALE_H 1

#define HAVE_LONG_DOUBLE 1

#define HAVE_LONG_LONG 1

#define HAVE_MALLOC_H 1

#define HAVE_MBRTOWC 1

#define HAVE_MEMORY_H 1

#define HAVE_PTRDIFF_T 1

#define HAVE_SIG_ATOMIC_T 1

#define HAVE_SNPRINTF 1

#define HAVE_STDINT_H 1

#define HAVE_STDINT_H_WITH_UINTMAX 1

#define HAVE_STDLIB_H 1

#define HAVE_STRCASECMP 1
#define strcasecmp _stricmp

#define HAVE_STRING_H 1

#define HAVE_STRNCASECMP 1
#define strncasecmp _strnicmp

#define HAVE_STRNLEN 1

#define HAVE_SYS_STAT_H 1

#define HAVE_SYS_TYPES_H 1

#define HAVE_VASPRINTF 1

#define HAVE_WCHAR_T 1

#define HAVE_WCRTOMB 1

#define HAVE_WCSLEN 1

#define HAVE_WCSNLEN 1

#define HAVE_WINT_T 1

#define PACKAGE_BUGREPORT ""

#define PACKAGE_NAME "glib-pkg-config"

#define PACKAGE_STRING "glib-pkg-config 2.58.0"

#define PACKAGE_TARNAME "glib-pkg-config"

#define PACKAGE_URL ""

#define PACKAGE_VERSION "2.58.0"

#define SIZEOF_CHAR 1

#define SIZEOF_INT 4

#define SIZEOF_LONG 4

#define SIZEOF_LONG_LONG 8

#define SIZEOF_SHORT 2

#define SIZEOF_SIZE_T 4

#define SIZEOF_SSIZE_T 4

#define SIZEOF_VOID_P 4

#define SIZEOF___INT64 8

#define STDC_HEADERS 1

#define THREADS_WIN32 1

#define USE_LIBICONV_NATIVE

#undef USE_SYSTEM_PCRE

//#define _GLIB_EXTERN __declspec(dllexport) extern
#define _GLIB_EXTERN

#define _GNU_SOURCE 1

#define _WIN32_WINNT 0x0601

